### ISSUE TITLE
Ajouter la licence

### ISSUE THREAD

**Issue by zhouzi** [zhouzi/broll#25]
- [ ] Augmenter le quota d'appels à l'API YouTube pour les détenteurs d'une licence #12 
- [ ] Réduire la durée de mise en cache des données pour les détenteurs d'une licence #11 
- [ ] Implémenter #17
- [ ] Faire en sorte que ça donne également accès à #5
